---
services:
  redis:
    image: aksaramaya/tc-redis
  web:
    image: aksaramaya/gagak
    ports:
      - "8080:8080"
    volumes:
      - ./settings.js:/opt/gagak/settings.js
    depends_on:
      - redis
version: "2"
